---@diagnostic disable: deprecated
return {
	assert         = assert,
	collectgarbage = require "collectgarbage",
	dofile         = dofile,
	error          = error,
	getfenv        = getfenv,
	getmetatable   = getmetatable,
	ipairs         = ipairs,
	load           = require "load",
	loadfile       = loadfile,
	loadstring     = loadstring,
	module         = require "module",
	newproxy       = newproxy,
	next           = next,
	pairs          = pairs,
	pcall          = pcall,
	print          = print,
	rawequal       = rawequal,
	rawget         = rawget,
	rawset         = rawset,
	require        = require "require",
	select         = require "select",
	setfenv        = setfenv,
	setmetatable   = setmetatable,
	tonumber       = tonumber,
	tostring       = tostring,
	type           = type,
	unpack         = require "unpack",
	xpcall         = xpcall,
};
